import { Card } from "./types";

/**
 * Mock card data for UI development.
 * Will be replaced with real data from Supabase/Scryfall.
 */
export const MOCK_DECK_CARDS: Card[] = [
  // Commander
  {
    id: "atraxa",
    name: "Atraxa, Praetors' Voice",
    imageUrl: "https://cards.scryfall.io/normal/front/d/0/d0d33d52-3d28-4635-b985-51e126289259.jpg",
    manaValue: 4,
    manaCost: "{G}{W}{U}{B}",
    type: "Commander",
    tags: ["Commander"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Creatures
  {
    id: "deepglow-skate",
    name: "Deepglow Skate",
    imageUrl: "https://cards.scryfall.io/normal/front/4/a/4a8b26dc-de39-4510-9571-6c4f3f5a7024.jpg",
    manaValue: 5,
    manaCost: "{4}{U}",
    type: "Creature",
    tags: ["Proliferate", "Finisher"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "evolution-sage",
    name: "Evolution Sage",
    imageUrl: "https://cards.scryfall.io/normal/front/9/6/969bf351-c7df-4eb0-8065-9b8d5233f8f3.jpg",
    manaValue: 3,
    manaCost: "{2}{G}",
    type: "Creature",
    tags: ["Proliferate"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "vorinclex-monstrous",
    name: "Vorinclex, Monstrous Raider",
    imageUrl: "https://cards.scryfall.io/normal/front/9/2/92613468-205e-488b-930d-11908477e9f8.jpg",
    manaValue: 6,
    manaCost: "{4}{G}{G}",
    type: "Creature",
    tags: ["Finisher"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "flux-channeler",
    name: "Flux Channeler",
    imageUrl: "https://cards.scryfall.io/normal/front/c/6/c6202e82-e159-482f-9224-292cb533171c.jpg",
    manaValue: 3,
    manaCost: "{2}{U}",
    type: "Creature",
    tags: ["Proliferate"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "ichor-rats",
    name: "Ichor Rats",
    imageUrl: "https://cards.scryfall.io/normal/front/2/0/2013aed6-7415-4bf0-a5bb-a7f60a45c2b2.jpg",
    manaValue: 3,
    manaCost: "{1}{B}{B}",
    type: "Creature",
    tags: ["Infect"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "bloom-hulk",
    name: "Pollenbright Druid",
    imageUrl: "https://cards.scryfall.io/normal/front/4/b/4b0f478c-54f8-4087-ad52-d089e2049dda.jpg",
    manaValue: 2,
    manaCost: "{1}{G}",
    type: "Creature",
    tags: ["Proliferate"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "birds-of-paradise",
    name: "Birds of Paradise",
    imageUrl: "https://cards.scryfall.io/normal/front/f/e/feefe9f0-24a6-461c-9ef1-86c5a6f33b83.jpg",
    manaValue: 1,
    manaCost: "{G}",
    type: "Creature",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Planeswalkers
  {
    id: "teferi-temporal",
    name: "Teferi, Temporal Pilgrim",
    imageUrl: "https://cards.scryfall.io/normal/front/8/6/86e7dca1-e850-4e8c-a0b5-7e7edb8bd50e.jpg",
    manaValue: 5,
    manaCost: "{3}{U}{U}",
    type: "Planeswalker",
    tags: ["Card Draw"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "liliana-dreadhorde",
    name: "Liliana, Dreadhorde General",
    imageUrl: "https://cards.scryfall.io/normal/front/d/7/d75ebba8-34ca-47a0-bf13-8318ad73b343.jpg",
    manaValue: 6,
    manaCost: "{4}{B}{B}",
    type: "Planeswalker",
    tags: ["Card Draw", "Removal"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "elspeth-suns-champion",
    name: "Elspeth, Sun's Champion",
    imageUrl: "https://cards.scryfall.io/normal/front/9/6/96f1d11a-084d-4de7-9ed4-33158113520c.jpg",
    manaValue: 6,
    manaCost: "{4}{W}{W}",
    type: "Planeswalker",
    tags: ["Token", "Removal"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "tamiyo-field",
    name: "Tamiyo, Field Researcher",
    imageUrl: "https://cards.scryfall.io/normal/front/9/f/9f61c200-0c99-47ad-8b24-4acbc6bfda8c.jpg",
    manaValue: 4,
    manaCost: "{1}{G}{W}{U}",
    type: "Planeswalker",
    tags: ["Card Draw"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Instants
  {
    id: "swords-plowshares",
    name: "Swords to Plowshares",
    imageUrl: "https://cards.scryfall.io/normal/front/7/d/7d839f21-68c7-47db-8407-ff3e2c3e13b4.jpg",
    manaValue: 1,
    manaCost: "{W}",
    type: "Instant",
    tags: ["Removal"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "path-to-exile",
    name: "Path to Exile",
    imageUrl: "https://cards.scryfall.io/normal/front/9/d/9d607a40-608a-44cd-b946-02636b5bea9f.jpg",
    manaValue: 1,
    manaCost: "{W}",
    type: "Instant",
    tags: ["Removal"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "counterspell",
    name: "Counterspell",
    imageUrl: "https://cards.scryfall.io/normal/front/1/b/1b73577a-8ca1-41d7-9b2b-7300286fde43.jpg",
    manaValue: 2,
    manaCost: "{U}{U}",
    type: "Instant",
    tags: ["Counter"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "heroic-intervention",
    name: "Heroic Intervention",
    imageUrl: "https://cards.scryfall.io/normal/front/c/5/c5e72882-dbf8-42d2-9a98-31f2f71e2ed9.jpg",
    manaValue: 2,
    manaCost: "{1}{G}",
    type: "Instant",
    tags: ["Protection"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "teferi-protection",
    name: "Teferi's Protection",
    imageUrl: "https://cards.scryfall.io/normal/front/7/7/77f130c7-0138-4a1a-9f67-62d2c302dc48.jpg",
    manaValue: 3,
    manaCost: "{2}{W}",
    type: "Instant",
    tags: ["Protection"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Sorceries
  {
    id: "kodamas-reach",
    name: "Kodama's Reach",
    imageUrl: "https://cards.scryfall.io/normal/front/9/7/979741db-e720-4efd-bc8e-2bf47e777ab3.jpg",
    manaValue: 3,
    manaCost: "{2}{G}",
    type: "Sorcery",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "cultivate",
    name: "Cultivate",
    imageUrl: "https://cards.scryfall.io/normal/front/8/4/84eb22e3-9323-4d8c-8e3c-5bd6c43ab18e.jpg",
    manaValue: 3,
    manaCost: "{2}{G}",
    type: "Sorcery",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "supreme-verdict",
    name: "Supreme Verdict",
    imageUrl: "https://cards.scryfall.io/normal/front/2/0/20b5fe42-929c-406d-9377-40b49f9d008e.jpg",
    manaValue: 4,
    manaCost: "{1}{W}{W}{U}",
    type: "Sorcery",
    tags: ["Removal"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Artifacts
  {
    id: "sol-ring",
    name: "Sol Ring",
    imageUrl: "https://cards.scryfall.io/normal/front/7/7/772edef7-2f17-4244-b1bb-4e7a53c99dbd.jpg",
    manaValue: 1,
    manaCost: "{1}",
    type: "Artifact",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "arcane-signet",
    name: "Arcane Signet",
    imageUrl: "https://cards.scryfall.io/normal/front/f/3/f3ee9829-f4c0-44a0-8252-4097402e2f8d.jpg",
    manaValue: 2,
    manaCost: "{2}",
    type: "Artifact",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "contagion-engine",
    name: "Contagion Engine",
    imageUrl: "https://cards.scryfall.io/normal/front/d/c/dce72636-08e4-484e-ad81-4d1597a31ffb.jpg",
    manaValue: 6,
    manaCost: "{6}",
    type: "Artifact",
    tags: ["Proliferate", "Removal"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "everflowing-chalice",
    name: "Everflowing Chalice",
    imageUrl: "https://cards.scryfall.io/normal/front/9/c/9cd8112f-21e0-4272-9f0d-14d1ef989779.jpg",
    manaValue: 0,
    manaCost: "{0}",
    type: "Artifact",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Enchantments
  {
    id: "doubling-season",
    name: "Doubling Season",
    imageUrl: "https://cards.scryfall.io/normal/front/8/6/8676d164-c76e-402b-a649-6ded3f549b6e.jpg",
    manaValue: 5,
    manaCost: "{4}{G}",
    type: "Enchantment",
    tags: ["Finisher"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "inexorable-tide",
    name: "Inexorable Tide",
    imageUrl: "https://cards.scryfall.io/normal/front/4/0/40441345-23ca-47e4-b349-bd13d986e41e.jpg",
    manaValue: 5,
    manaCost: "{3}{U}{U}",
    type: "Enchantment",
    tags: ["Proliferate"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "rhystic-study",
    name: "Rhystic Study",
    imageUrl: "https://cards.scryfall.io/normal/front/d/6/d6914dba-0d27-4055-ac34-b3ebf5802c71.jpg",
    manaValue: 3,
    manaCost: "{2}{U}",
    type: "Enchantment",
    tags: ["Card Draw"],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "smothering-tithe",
    name: "Smothering Tithe",
    imageUrl: "https://cards.scryfall.io/normal/front/f/2/f25a4bbe-2af0-4d4a-95d4-d52c5937c747.jpg",
    manaValue: 4,
    manaCost: "{3}{W}",
    type: "Enchantment",
    tags: ["Ramp"],
    quantity: 1,
    allowsMultipleCopies: false,
  },

  // Lands (non-basic)
  {
    id: "command-tower",
    name: "Command Tower",
    imageUrl: "https://cards.scryfall.io/normal/front/7/e/7eafe88e-ab38-442c-b147-bb01cc81178d.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "breeding-pool",
    name: "Breeding Pool",
    imageUrl: "https://cards.scryfall.io/normal/front/b/b/bb54f87e-56e2-4dc0-8351-67df0404d7ef.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "watery-grave",
    name: "Watery Grave",
    imageUrl: "https://cards.scryfall.io/normal/front/7/d/7d4595f2-9297-40dc-b2dd-7144bbb401f7.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "godless-shrine",
    name: "Godless Shrine",
    imageUrl: "https://cards.scryfall.io/normal/front/c/e/ced4c824-2dfc-42ae-84e6-09f8e3f51b5b.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "temple-garden",
    name: "Temple Garden",
    imageUrl: "https://cards.scryfall.io/normal/front/2/b/2b9b0195-bfe5-4a3d-ac1a-f99d417ca402.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "hallowed-fountain",
    name: "Hallowed Fountain",
    imageUrl: "https://cards.scryfall.io/normal/front/f/9/f97a6d34-03ab-49f1-b02e-405b733f8843.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  {
    id: "overgrown-tomb",
    name: "Overgrown Tomb",
    imageUrl: "https://cards.scryfall.io/normal/front/e/f/eff1f52c-5c43-4260-aaa0-6920846a191c.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 1,
    allowsMultipleCopies: false,
  },
  // Basic Lands (allow multiple copies)
  {
    id: "island-1",
    name: "Island",
    imageUrl: "https://cards.scryfall.io/normal/front/b/2/b2afe54e-c376-4e23-9a3d-cf3b1437a587.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 5,
    allowsMultipleCopies: true,
  },
  {
    id: "plains-1",
    name: "Plains",
    imageUrl: "https://cards.scryfall.io/normal/front/5/c/5cbfbafa-f58f-40b2-a374-68ac35b77d89.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 4,
    allowsMultipleCopies: true,
  },
  {
    id: "swamp-1",
    name: "Swamp",
    imageUrl: "https://cards.scryfall.io/normal/front/a/c/ac18b50c-7446-42b7-a29e-f377a0178c70.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 4,
    allowsMultipleCopies: true,
  },
  {
    id: "forest-1",
    name: "Forest",
    imageUrl: "https://cards.scryfall.io/normal/front/a/e/aea5c36b-c107-4daf-bedb-507b4cd64724.jpg",
    manaValue: 0,
    manaCost: "",
    type: "Land",
    tags: [],
    quantity: 5,
    allowsMultipleCopies: true,
  },
];

export const EMPTY_DECK_CARDS: Card[] = [];
